config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'guests#new'
  resources :guests, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      UserMailer.invitation(@guest).deliver_now
      UserMailer.invitation_reponse(@guest).deliver_now
      redirect_to new_guest_path, flash: {success: 'Votre message a été envoyé'}
    end
  end

  def index
  end

  private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :lover, :children, :coming, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<div class="form-guest">
  <p class="ecriture-form">Réponse souhaitée avant le 30.06.2022</p>
  <%= simple_form_for @guest do |f| %>
      <div class="contact-info">
        <%= f.input :first_name,
                    as: :string,
                    label: "Prénom" %>
        <%= f.input :last_name,
                    as: :string,
                    label: "Nom" %>
                    <div class="lover-form">
        <%= f.input :lover,
                    :collection => [[true, 'Oui'], [false, 'Non']],
                    :label_method => :last,
                    :value_method => :first,
                    as: :radio_buttons,
                    label: "Conjoint" %>
                    </div>
        <%= f.input :children,
                    as: :integer,
                    label: "Nombre d'enfant" %>
        <%= f.input :coming,
                    :collection => [[true, 'Oui'], [false, 'Non']],
                    :label_method => :last,
                    :value_method => :first,
                    as: :radio_buttons,
                    label: "Présent" %>
        <%= f.input :comment,
                    as: :text,
                    label: "Avez-vous un régime alimentaire/allergie particulier.e ?" %>
      </div>
      <div class="d-flex flex-row-reverse mt-4 justify-content-center">
        <%= f.submit "J’envoie ma réponse aux futurs mariés", class: "bouton" %>
      </div>
      <div class="message-flash"><%= flash[:success] %></div>
    <% end %>
</div>

app/views/guests/index.html.erb
<div class="ligne-beige">
  <%= link_to new_guest_path, class: "lien-galerie" do %>
    <p class="bouton">Retour</p>
  <% end %>
</div>
<div class="row d-flex justify-content-center">
  <%= image_tag "leila-1.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-2.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-3.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-4.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-5.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-6.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-7.jpeg", class: "photo-couple" %>
  <%= image_tag "leila-8.jpeg", class: "photo-couple" %>
</div>

<div class="ligne-beige-basse">
<p class="verset">1 corinthiens 13:4-8 " L'amour est patient, il est plein de bonté; l'amour n'est pas envieux; l'amour ne se vante pas, il ne s'enfle pas d'orgueil, il ne fait rien de malhonnête, il ne cherche pas son intérêt, il ne s'irrite pas, il ne soupçonne pas le mal, il ne se réjouit pas de l'injustice,  mais il se réjouit de la vérité ; il pardonne tout, il croit tout, il espère tout, il supporte tout. L'amour ne meurt jamais."</p>
</div>

app/views/guests/new.html.erb
<div class="cover">
  <%= image_tag "info-mariage.jpg", class: "invit" %>
</div>
<div class="ligne-beige">
  <%= link_to guests_path, class: 'lien-galerie' do %>
      <p class="bouton">Galerie photo</p>
  <% end %>
</div>
<div class="photo-form">
<%= image_tag "leila-9.jpeg", class: "photo-couple" %>
<%= render "guests/form", guest: @guest %>
</div>
<div class="info-complementaire">
  <div class="info-partie">
    <p class="titre-info">Informations complémentaires</p>
  </div>
  <div class="info-partie">
    <div>
      <p class="texte-info text-center">Vous pourrez trouver une cagnotte sur place pour la lune de miel.</p>
      <p class="texte-info text-center">Prévoyez de manger entre la mairie et la cérémonie religieuse (Le vin d'honneur ne commence qu'à 15h30)</p>
      <p class="texte-info text-center">️Il y aura un retour de mariage le lendemain dans la salle du manoir qui commencera à partir de 11h30.</p>
      <p class="texte-info text-center">Pour le stationnement a côté de la mairie de Saint-Brieuc, possibilité de se garer  2T rue du parc au parking administratif (5 min à pied de la mairie, gratuit) ou au parking poulain corbier (payant) a coté de la mairie.</p>
      <p class="texte-info text-center">Au manoir, il y a un parking sur place de 50 places, privilégiez le covoiturage entre vous.</p>
      <p class="texte-info text-center">La mairie n'est pas obligatoire, vous pouvez venir à partir de 13h30 au Manoir pour la cérémonie religieuse.</p>
      <p class="texte-info text-center">Les robes et jupes blanches sont proscrites (sauf pour la mariée 😉 )</p>
    </div>
  </div>
</div>
<div class="adress">
  <h2 class="titre">Les adresses</h2>
  <div class="places">
    <%= image_tag "manoir.png", class: "places-photo" %>
    <%= image_tag "mairie.png", class: "places-photo" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariageLeilaRaph</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>